dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
# networks:
#   default: development
#   rinkeby:
#   mainnet-fork-dev:
#   development:
#   ganache-local:
wallets:
  from_key: ${PRIVATE_KEY}
